### PR TITLE
Added Technique and Updated Banner Version

### PR DESCRIPTION
**Pull request by NoPurposeInLife**
Tested locally

image

### CODE REVIEW

**Comment by codewatchorg** [comment]
This is the default technique, which since it is default is what the extension already uses. I thought you wanted to limit attacks to specific techniques (though I can use this as the basis for adding an option to just use specific techniques OR the default)

**Comment by codewatchorg** [comment]
nvm, I am dumb, you created a text field and just set the default to BEUSTQ. I will review and merge

**Comment by NoPurposeInLife** [comment]
Hey! No worries, I should've added a screenshot on the extension's UI from my end, apologies & thanks again!

**Comment by codewatchorg** [comment]
I added the code and will submit a pull request with Portswigger.

**Pull request closed without merging**
